name: lukyui
description: "Make beautiful UI with ease. LukyUI is a Flutter UI library that provides a collection of pre-designed widgets and components to help developers create stunning user interfaces quickly and efficiently."
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^5.1.0
  intl: ^0.20.2
  uuid: ^4.5.1
  provider: ^6.1.4
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
